[2025-01-03T07:35:15.380+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-03T07:35:15.399+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.process_user scheduled__2025-01-02T00:00:00+00:00 [queued]>
[2025-01-03T07:35:15.408+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.process_user scheduled__2025-01-02T00:00:00+00:00 [queued]>
[2025-01-03T07:35:15.409+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-03T07:35:15.423+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_user> on 2025-01-02 00:00:00+00:00
[2025-01-03T07:35:15.438+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-03T07:35:15.439+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', 'scheduled__2025-01-02T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpckqg8orr']
[2025-01-03T07:35:15.441+0000] {standard_task_runner.py:72} INFO - Started process 108 to run task
[2025-01-03T07:35:15.441+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask process_user
[2025-01-03T07:35:15.499+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.process_user scheduled__2025-01-02T00:00:00+00:00 [running]> on host a67ecbd59b00
[2025-01-03T07:35:15.579+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='process_user' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-02T00:00:00+00:00'
[2025-01-03T07:35:15.580+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-03T07:35:15.581+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-03T07:35:15.581+0000] {logging_mixin.py:190} INFO - Current task name:process_user state:running start_date:2025-01-03 07:35:15.400194+00:00
[2025-01-03T07:35:15.582+0000] {logging_mixin.py:190} INFO - Dag name:user_processing and current dag run status:running
[2025-01-03T07:35:15.582+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-03T07:35:15.590+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/user_processing.py", line 12, in _process_user
    user = user['results'][0]
           ~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2025-01-03T07:35:15.606+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-03T07:35:15.607+0000] {logging_mixin.py:190} INFO - Task start:2025-01-03 07:35:15.400194+00:00 end:2025-01-03 07:35:15.605538+00:00 duration:0.205344
[2025-01-03T07:35:15.607+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_user> dag:<DAG: user_processing> dagrun:<DagRun user_processing @ 2025-01-02 00:00:00+00:00: scheduled__2025-01-02T00:00:00+00:00, state:running, queued_at: 2025-01-03 07:35:05.385903+00:00. externally triggered: False>
[2025-01-03T07:35:15.608+0000] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object is not subscriptable
[2025-01-03T07:35:15.608+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=user_processing, task_id=process_user, run_id=scheduled__2025-01-02T00:00:00+00:00, execution_date=20250102T000000, start_date=20250103T073515, end_date=20250103T073515
[2025-01-03T07:35:15.624+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-03T07:35:15.625+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 32 for task process_user ('NoneType' object is not subscriptable; 108)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/user_processing.py", line 12, in _process_user
    user = user['results'][0]
           ~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2025-01-03T07:35:15.656+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-03T07:35:15.679+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-03T07:35:15.693+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
