[2025-01-05T05:53:40.054+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T05:53:40.073+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.process_user manual__2025-01-05T05:53:24.262265+00:00 [queued]>
[2025-01-05T05:53:40.083+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.process_user manual__2025-01-05T05:53:24.262265+00:00 [queued]>
[2025-01-05T05:53:40.084+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-05T05:53:40.105+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_user> on 2025-01-05 05:53:24.262265+00:00
[2025-01-05T05:53:40.115+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=477) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-05T05:53:40.117+0000] {standard_task_runner.py:72} INFO - Started process 479 to run task
[2025-01-05T05:53:40.119+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', 'manual__2025-01-05T05:53:24.262265+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpx9vmexlz']
[2025-01-05T05:53:40.121+0000] {standard_task_runner.py:105} INFO - Job 51: Subtask process_user
[2025-01-05T05:53:40.184+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.process_user manual__2025-01-05T05:53:24.262265+00:00 [running]> on host a67ecbd59b00
[2025-01-05T05:53:40.300+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='process_user' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T05:53:24.262265+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T05:53:24.262265+00:00'
[2025-01-05T05:53:40.302+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-05T05:53:40.303+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-05T05:53:40.304+0000] {logging_mixin.py:190} INFO - Current task name:process_user state:running start_date:2025-01-05 05:53:40.074094+00:00
[2025-01-05T05:53:40.304+0000] {logging_mixin.py:190} INFO - Dag name:user_processing and current dag run status:running
[2025-01-05T05:53:40.305+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T05:53:40.316+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/user_processing.py", line 14, in _process_user
    user = user['results'][0]
           ~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2025-01-05T05:53:40.334+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-05T05:53:40.335+0000] {logging_mixin.py:190} INFO - Task start:2025-01-05 05:53:40.074094+00:00 end:2025-01-05 05:53:40.333809+00:00 duration:0.259715
[2025-01-05T05:53:40.336+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_user> dag:<DAG: user_processing> dagrun:<DagRun user_processing @ 2025-01-05 05:53:24.262265+00:00: manual__2025-01-05T05:53:24.262265+00:00, state:running, queued_at: 2025-01-05 05:53:24.277972+00:00. externally triggered: True>
[2025-01-05T05:53:40.337+0000] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object is not subscriptable
[2025-01-05T05:53:40.338+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=user_processing, task_id=process_user, run_id=manual__2025-01-05T05:53:24.262265+00:00, execution_date=20250105T055324, start_date=20250105T055340, end_date=20250105T055340
[2025-01-05T05:53:40.352+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T05:53:40.353+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 51 for task process_user ('NoneType' object is not subscriptable; 479)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/user_processing.py", line 14, in _process_user
    user = user['results'][0]
           ~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2025-01-05T05:53:40.375+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-05T05:53:40.402+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T05:53:40.409+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
